package FestivalPlanner.Agenda;

import FestivalPlanner.GUI.AgendaGUI.PopUpGUI.AbstractDialogPopUp;
import java.io.*;

/**
 * Contains all methods needed to save data generated by our software.
 */
public class SaveHandler implements Serializable {

    /**
     * Saves an Agenda object; writes all data from an instance of
     * <a href="{@docRoot}/FestivalPlanner/Agenda/Agenda.html">Agenda</a> to a file created
     * in a dialog.
     * @param fileName  name of file to write data to
     * @param agenda  instance of Agenda to save
     */
    public void writeAgendaToFile(String fileName, Agenda agenda){
        try(ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream(fileName))){
            output.writeObject(agenda);
        } catch (Exception e){
            AbstractDialogPopUp.showExceptionPopUp(e);
        }
    }

    /**
     * Loads an Agenda object; replaces all this agenda values with the ones the user loads.
     * @param fileName  name of file to read data from
     * @return  a new Agenda with data from the selected file
     */
    public Agenda readAgendaFromFile(String fileName){
        Agenda agenda = new Agenda();

        try(ObjectInputStream inputStream = new ObjectInputStream(new FileInputStream(fileName))){

            //Sets the new instance of Agenda to the one from the ObjectInputStream.
            agenda = (Agenda) (inputStream.readObject());

        } catch (Exception e){
            AbstractDialogPopUp.showExceptionPopUp(e);
        }

        return agenda;
    }
}